

services:
  fastapi:
    build: .
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    volumes:
      - translations-db:/app
    env_file:
      - .env

  streamlit:
    build: .
    command: ["streamlit", "run", "app.py", "--server.port=8080", "--server.enableCORS=false"]
    ports:
      - "8080:8080"
    volumes:
      - translations-db:/app
    environment:
      - FASTAPI_HOST=fastapi

volumes:
  translations-db:
