version: '3.8'

services:
  fastapi:
    build: .
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    depends_on:
      - streamlit

  streamlit:
    build: .
    command: ["streamlit", "run", "app.py", "--server.port=80", "--server.enableCORS=false"]
    ports:
      - "80:80"
    volumes:
      - .:/app
